"""initial migration

Revision ID: 53001e5fbec1
Revises: a0db87865b0a
Create Date: 2025-03-24 18:26:02.960477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53001e5fbec1'
down_revision = 'a0db87865b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('old_price')

    # ### end Alembic commands ###
