"""initial migration

Revision ID: 832744bbe3ad
Revises: a3d61bcb5ca0
Create Date: 2025-04-14 15:11:50.037788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832744bbe3ad'
down_revision = 'a3d61bcb5ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
