"""initial migration

Revision ID: 96de24de63ee
Revises: d390eebdb53c
Create Date: 2025-04-04 00:07:00.488878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96de24de63ee'
down_revision = 'd390eebdb53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=300), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')

    # ### end Alembic commands ###
