"""initial migration

Revision ID: 9c2f152f6253
Revises: d244f5be7595
Create Date: 2025-04-23 12:53:08.613763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2f152f6253'
down_revision = 'd244f5be7595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url_title', sa.String(length=400), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Enum('home', 'product_list', 'product_details', name='sitebannerposition'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_banner')
    # ### end Alembic commands ###
